### ISSUE TITLE
Typo: Basic Node and Express - Chain Middleware to Create a Time Server

### ISSUE THREAD

**Issue by mpmaan** [freeCodeCamp/curriculum#114]
**Describe the bug**
Incorrect spelling of **hypothetical**

**Screenshots**
![screenshot-2018-7-6 welcome to learn freecodecamp 1](https://user-images.githubusercontent.com/34267628/42365598-9084216a-811c-11e8-9266-268a731ec103.png)

**Comment by johnkennedy9147** [comment]
closed by #115
