### ISSUE TITLE
404 error, page not found on react challenge.

### ISSUE THREAD

**Issue by wadleo** [freeCodeCamp/curriculum#155]
This [bug](https://github.com/freeCodeCamp/learn/issues/236) was reported in the freecodecamp repo, below are the full details to it.
In the Front End Libraries Certification: React Challenge there is a [challenge](https://learn.freecodecamp.org/front-end-libraries/react/introducing-inline-styles) named

Introducing Inline Styles

in which there's a link to an [article](https://learn.freecodecamp.org/define-an-html-class-in-jsx) and when I click in the link it redirects me to a 404 page. That means the page does not exist anymore.

**Comment by Nirajn2311** [comment]
Can you close this issue as it is solved in #151

**Comment by johnkennedy9147** [comment]
@Nirajn2311 thanks for the heads up. Issue closed.
