### ISSUE TITLE
Indent sample code in lesson description

### ISSUE THREAD

**Issue by Bouncey** [freeCodeCamp/curriculum#16]
@thefifthisa commented on [Wed Jun 13 2018](https://github.com/freeCodeCamp/learn/issues/172)

#### Describe your problem and - if possible - how to reproduce it
Minor thing, but I think it would improve readability if the sample code below was properly indented like in other lesson descriptions.

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/es6/prevent-object-mutation

#### If possible, add a screenshot here
![es6_prevent object mutation](https://user-images.githubusercontent.com/30595954/41340428-e7531992-6f29-11e8-8311-a48756d151ab.png)

---

@Nirajn2311 commented on [Wed Jun 13 2018](https://github.com/freeCodeCamp/learn/issues/172#issuecomment-397070101)

I’ll see what I can do about it.

---

@Nirajn2311 commented on [Fri Jun 15 2018](https://github.com/freeCodeCamp/learn/issues/172#issuecomment-397585710)

There is a mistake in this challenge's code of FCC's curriculum node_module

**Comment by Nirajn2311** [comment]
After two days of digging I found the root of the problem and it is in package.json in learn repo.
When you do yarn install it downloads @freecodecamp/curriculum 1.0.4 version, as it is set as required version in the json file, which has some typos so the package.json in learn repo should be updated.
Anyone is free to do this.
Ignore the previous comment as I still hadn't checked curriculum repo.

**Comment by moT01** [comment]
I made a pr on the main repo to fix all the formatting in the seed files - there was at least several dozen challenges that needed formatting in the description

**Comment by Nirajn2311** [comment]
@Bouncey @moT01 I have doubt whether the changes in the seed files will reflect in learn repo. Also the learn repo depends on the curriculum module.

**Comment by moT01** [comment]
I suppose since learn is now getting the challenges from this repo I should assume that changes over on the main repo wont show up - if that's the case we should maybe merge the pr's involving seed files over on the main repo and move the files over here - and maybe delete them from over there to avoid confusion - not sure where we want issues to be made - maybe we should close the over there and move them over here as well

**Comment by Nirajn2311** [comment]
That’s the doubt many of us have(as I and @anku255 discussed in Gitter), if any main contributors commented on it then some of us could help in the transferring.
