### ISSUE TITLE
Provide better instructions for 'has' method in Create a Map Data Structure challenge

### ISSUE THREAD

**Issue by shimphillip** [freeCodeCamp/curriculum#193]
#### Is your feature request related to a problem? Please describe.

https://learn.freecodecamp.org/coding-interview-prep/data-structures/create-a-map-data-structure/.
Instructions for 'has' method in the challenge is pretty ambiguous unlike descriptions of other methods in the same challenge. It lacks proper explanation of what the method is expecting.
 
#### Describe the solution you'd like

Change the text from "has returns a boolean for the presence or absence of an item" to "has accepts a key and returns true or false based on the presence of a key" 

#### Describe alternatives you've considered

None.

**Comment by Nirajn2311** [comment]
Working on it.
