### ISSUE TITLE
https://github.com/freeCodeCamp/freeCodeCamp/issues/17951

### ISSUE THREAD

**Issue by D3Portillo** [freeCodeCamp/curriculum#197]
https://github.com/freeCodeCamp/freeCodeCamp/issues/17951 still persists

**Comment by jocharles57** [comment]
Yep, still happening.

**Comment by johnkennedy9147** [comment]
this is fixed in https://github.com/freeCodeCamp/curriculum/pull/189
the fix wont go live till the next release
