### ISSUE TITLE
Create Grids within Grids can be passed without doing anything

### ISSUE THREAD

**Issue by JasonXiao2007** [freeCodeCamp/curriculum#198]
#### Describe the bug
This challenge can be passed without doing any work. 

#### To Reproduce
1. Go to 'https://learn.freecodecamp.org/responsive-web-design/css-grid/create-grids-within-grids/'
2. Click on 'Run the Tests'
3. See error (You just passed without doing anything)

#### Expected behavior
This challenge will need to be completed before it can be passed.

#### Desktop (please complete the following information):
 - OS: [OSX 10.13.6 High Sierra]
 - Browser [Chrome]
 - Version [Version 67.0.3396.99]

#### Additional context
This was submitted a while ago on forum too: https://forum.freecodecamp.org/t/create-grids-within-grids/198349

**Comment by gforce2k5** [comment]
i'll work on it
