### ISSUE TITLE
Error causing test to fail - Create a Horizontal Line Using <hr> tag

### ISSUE THREAD

**Issue by myDeveloperJourney** [freeCodeCamp/curriculum#202]
#### Describe the bug
I've attempted solving this exercise several times. The solution to solving this exercise is relatively simple, it just requires an `<hr>` tag to be placed between the `<h4>` title tag and the first `<p>` tag that follows it.

However, when submitting this solution, once of the tests fail:

`"The hr tag should come between the title and the paragraph."`

I've also attempted to take the following exercises code and paste it into the IDE as well, but it didn't work either.

I've included screen shots below

#### To Reproduce
1. Go to 'https://learn.freecodecamp.org/responsive-web-design/applied-visual-design/create-a-horizontal-line-using-the-hr-element'
2. Click on 'Run the tests'
3. See error

#### Expected behavior
Both tests should pass

#### Screenshots
<img width="1674" alt="screen shot 2018-07-29 at 1 36 32 pm" src="https://user-images.githubusercontent.com/20377140/43369084-9a74fe3a-9335-11e8-83aa-9f41d6515d2f.png">
<img width="1672" alt="screen shot 2018-07-29 at 1 39 33 pm" src="https://user-images.githubusercontent.com/20377140/43369085-9a83bd30-9335-11e8-8cf5-9cec214c68f9.png">
<img width="1673" alt="screen shot 2018-07-29 at 1 41 11 pm" src="https://user-images.githubusercontent.com/20377140/43369086-9a95a4fa-9335-11e8-89c9-0597b87ef7c2.png">

#### Desktop (please complete the following information):
 - OS: macOS High Sierra - 10.13.6 
 - Browser: Chrome
 - Version: 67.0.3396.99

**Comment by johnkennedy9147** [comment]
this is already fixed in #189 it will go live at next release
