### ISSUE TITLE
Positive and Negative Lookahead bug

### ISSUE THREAD

**Issue by davewburns** [freeCodeCamp/curriculum#209]
#### Describe the bug
The test will pass with only one number present using this regex `/(?=\w{5})(?=\D*\d)/`

#### To Reproduce
1. Go to '[...](https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/regular-expressions/positive-and-negative-lookahead)'
2. Use `/(?=\w{5})(?=\D*\d)/` as the code solution.
3. The test will pass.

#### Expected behavior
The test should fail as a word with only one number at the end will be found with the regex.  This was tested on [regextester.com](https://www.regextester.com/?fam=104369)

#### Desktop (please complete the following information):
 - OS: [Debian Linux]
 - Browser [Chrome]

**Comment by joshalling** [comment]
It looks like there is no test present to assert that an input with only 1 digit like `abcd1` fails. I can take this one.
