### ISSUE TITLE
The definition of complementary colors.

### ISSUE THREAD

**Issue by kevinsmithwebdev** [freeCodeCamp/curriculum#221]
A few days ago the section on complementary colors was edited to list orange as the complementary color of blue. 

This is a contentious subject with a lot of people because a lot of us (including me) were taught the outdated RYB color model in school and that kind of sticks with us. Most people do not realize that that is no longer accepted and the preference is for the additive RGB or subtractive CMY. Of course, computer graphics are based on the RGB model.

I know people get heated about this subject. People have a habit of assuming that what they were taught in second grade is the gospel truth and can't conceive that Mrs. Magillicutty could be wrong. And sadly, many people have very firm opinions on this without having researched the subject. Color theory is a very complex science and should not be thrown together willy-nilly.

I suggest changing it back to the modern scientific understanding of color, based on the RGB model - the very color model that computer monitors use. A brief note could be added to explain that this is different than what many people were taught and provide a link to relevant material. Wikipedia for example has [a pretty straightforward article](https://en.wikipedia.org/wiki/Complementary_colors) explaining the change.

**Comment by kevinsmithwebdev** [comment]
So, no one has any thoughts on this? Shall I assume that silence is consent?

**Comment by beaucarnes** [comment]
You are correct. This should be changed back to how it was.

**Comment by Ashera138** [comment]
Sorry Mrs. Magillicutty - it's time to go with the modern, scientific consensus. My vote is for the RGB model. 👍

**Comment by scissorsneedfoodtoo** [comment]
@kevinsmithwebdev, yes, you're absolutely correct. Should have really done more reading up on the subject before I merged that PR!

Would you be interested in changing the updating the challenge description to mention the RGB model and so yellow is the complementary color again? If not, @Ashera138, would you be interested in making the change?

**Comment by kevinsmithwebdev** [comment]
I can take care of it if it's alright - I could use the practice.

**Comment by scissorsneedfoodtoo** [comment]
Okay! Thank you again for catching this. Looking forward to your PR :+1:
