### ISSUE TITLE
Update text in Applied Visual Design challenge

### ISSUE THREAD

**Issue by beaucarnes** [freeCodeCamp/curriculum#24]
#### Describe your problem and - if possible - how to reproduce it
In the challenge, "Applied Visual Design: Use the u Tag to Underline Text", there is text that should be changed to make more sense.

It says:
> Wrap the `u` tag around the text "Ph.D. students". It should not include the parent `div` that has the class of `cardText`.

I think the second sentence should be removed. It is confusing and adds nothing to the challenge.

#### Add a Link to the page with the problem

https://learn.freecodecamp.org/responsive-web-design/applied-visual-design/use-the-u-tag-to-underline-text

**Comment by johnkennedy9147** [comment]
@beaucarnes For the tests to pass you need to wrap `Ph.D. students` only, if you wrap round anything else, even an additional space a test will fail.  So we probably want to replace rather than remove the sentence so that we clearly set out what is required.

**Comment by sergiorojasa** [comment]
I would like to work on this issue.

**Comment by anku255** [comment]
Hi! @ChrisLMartin! Seems like you have made a [commit](https://github.com/ChrisLMartin/curriculum/commit/2d3d51c2a59e1b9c67e2eb1ad0e45677f73b6585) to fix this issue but I can't find any PR. Can you please give us an update?

**Comment by ChrisLMartin** [comment]
Hi @anku255, I was hoping to get rid of it, but not sure how.

**Comment by RobAnthony01** [comment]
@ChrisLMartin What do you mean 'get rid of it'?

**Comment by Nirajn2311** [comment]
So @ChrisLMartin are you working on this?

**Comment by nathanhannig** [comment]
I think he doesn't want the commit to show on this issue and that he will not be working on this.
