### ISSUE TITLE
"Responsive Web Design Principles: Create a Media Query" test is not forgiving.

### ISSUE THREAD

**Issue by psyperl** [freeCodeCamp/curriculum#271]
#### Describe the bug
"Responsive Web Design Principles: Create a Media Query" test is not forgiving.

#### To Reproduce
Link of challenge: https://learn.freecodecamp.org/responsive-web-design/responsive-web-design-principles/create-a-media-query/

the test wouldn't pass with
```
  @media ( max-height: 800px ) {
    p {
      font-size: 10px;
    }
  }
```

it would only pass
```
  @media (max-height: 800px) {
    p {
      font-size: 10px;
    }
  }
```

difference is an extra spaces inside the parenthesis.

#### Expected behavior
should pass for both of the code

#### Screenshots
![screen shot 2018-08-24 at 22 38 24](https://user-images.githubusercontent.com/28307592/44593768-81690a80-a7ee-11e8-8e9b-dbd6f01877a6.png)

#### Desktop (please complete the following information):
* Browser Name: Safari
* Browser Version: Version 11.1.2 (13605.3.8)
* Operating System: macOS High Sierra Version 10.13.6

#### Additional context
None

**Comment by gareth-d85** [comment]
I have the Same issue.
running firefox on Linux.

**Comment by Nirajn2311** [comment]
I’ll work on it.
