### ISSUE TITLE
Destructuring with the Rest Operator , assertion accepts an empty array

### ISSUE THREAD

**Issue by parent-tobias** [freeCodeCamp/curriculum#281]
#### Describe the bug
In the assignment [ES6: Use Destructuring Assignment with the Rest Operator to Reassign Array Elements](https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/es6/use-destructuring-assignment-with-the-rest-operator-to-reassign-array-elements/), if an empty array is returned, the assignment is passed.

#### To Reproduce
1. Go to 'https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/es6/use-destructuring-assignment-with-the-rest-operator-to-reassign-array-elements/'
2. Return an empty array from the function
3. Run tests

#### Expected behavior
The returned array should be the length of the passed array, less two. The assertion `assert(arr.every((v, i) => v === i + 3));` returns true because it is an empty array, thus passing an incorrect response.

#### Desktop (please complete the following information):
 - OS: Win10
 - Browser: Chrome
 - Version Version 68.0.3440.106

**Comment by ojeytonwilliams** [comment]
I've taken a look at this and it does need a bit of work.  Should have a PR soon.
