### ISSUE TITLE
Typo in curriculum/challenges/01-responsive-web-design/css-flexbox.json

### ISSUE THREAD

**Issue by devragj** [freeCodeCamp/curriculum#287]
#### Describe the bug
The description of wrap-reverse has a typo.
This is in line 936 of the file css-flexbox.json.
Currently the description of wrap-reverse is:
"wrap-reverse: wraps items from bottom-to-top if they are in a row, or left-to-right if they are in a column."

It should be:
wrap-reverse: wraps items from bottom-to-top if they are in a row, or right-to-left if they are in a column.

**Comment by robinmetral** [comment]
Fixing this
