### ISSUE TITLE
Change description in lesson Basic CSS: Cascading CSS variables, :root definition and usage

### ISSUE THREAD

**Issue by mul53** [freeCodeCamp/curriculum#314]
#### Describe the bug and reproduce it
The lesson states:
_"You can think of the :root element as a container for your entire HTML document, in the same way that an html element is a container for the body element."_

#### Desktop (please complete the following information):
 - OS: Ubuntu,
 - Browser: chrome,
 - Browser Version: Version 67.0.3396.99

#### Additional context
The issue was raised in the freeCodeCamp/freeCodeCamp repo [#18116](https://github.com/freeCodeCamp/freeCodeCamp/issues/18116) but the fix occurs in this repo.

**Comment by randelldawson** [comment]
@mul53 After reading the [MDN listing on the subject](https://developer.mozilla.org/en-US/docs/Web/CSS/:root), I think HTML is the correct term to use here.
