### ISSUE TITLE
Redundant/Repetitive text in guide from previous challenge

### ISSUE THREAD

**Issue by mpmaan** [freeCodeCamp/curriculum#36]
**Describe the bug**

The guide in the first challenge contains the same redundant text from the second challenge.
1) https://learn.freecodecamp.org/front-end-libraries/bootstrap/create-a-custom-heading
2) https://learn.freecodecamp.org/front-end-libraries/bootstrap/use-the-bootstrap-grid-to-put-elements-side-by-side

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

This is the redundant text.
`Take for example Bootstrap's........................wide the element should be.`

**Comment by gforce2k5** [comment]
I want to have a go on this. The text should be removed from the second challenge right?

**Comment by thatnini** [comment]
It needs to be removed from [https://learn.freecodecamp.org/front-end-libraries/bootstrap/create-a-custom-heading/](https://learn.freecodecamp.org/front-end-libraries/bootstrap/create-a-custom-heading/) as it comes later in the curriculum than the other one.

Also I think you can remove `In the Cat Photo App that we're building, ....` x2 and `Put the Like, Info and Delete buttons side-by-side...` paragraphs as well as these don't make sense in this challenge.
