### ISSUE TITLE
Running unpack and then repack removes translations from challenge json files

### ISSUE THREAD

**Issue by gforce2k5** [freeCodeCamp/curriculum#42]
**Describe the bug**
When running `npm run unpack`, then `npm run repack`, translations gets deleted from challenge json file

**To Reproduce**
1. Run `npm run unpack`
2. Make changes in unpacked HTML files
3. Run `npm run repack`
4. Go to any challenge json file, see that translations are not there

**Expected behavior**
Translations should not get deleted from json files

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**

**Comment by gforce2k5** [comment]
I'll be happy to try and fix this issue

**Comment by raisedadead** [comment]
@gforce2k5 go ahead. It would be awesome if you can get the scripts working again.

**Comment by Flarp** [comment]
The `releasedOn` field is deleted as well (at least on my machine)

https://github.com/Flarp/curriculum/commit/177f34419ac1e9c914d2ad1d571da0f41f8946df

**Comment by wadleo** [comment]
Not only the releasedOn field is deleted, but the isRequired and react fields are also deleted, as seen below (I did a git diff, so I noticed the removals and re-indenting of the code). It also reindents the code. 
![gnome-shell-screenshot-tg4tlz](https://user-images.githubusercontent.com/11006276/42762103-4f72f21c-8907-11e8-82ec-9ae74cc08bd2.png)
