### ISSUE TITLE
Telephone Number Validator - Examples are not presented on separate lines as expected

### ISSUE THREAD

**Issue by huyenltnguyen** [freeCodeCamp/curriculum#47]
**Bug:**
In the challenge description, the examples of valid phone number formats are not presented on separate lines as expected.

Link to the challenge: https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/javascript-algorithms-and-data-structures-projects/telephone-number-validator

**Solution:**
This is because HTML doesn't render `\n` to a new line, but a single space instead. We can fix it by replacing all the `\n` characters with `<br>` tags. Here is the line that needs to be edited:
https://github.com/freeCodeCamp/curriculum/blob/34f45d25fb0f2b6959539a892892e48b5768fc57/challenges/02-javascript-algorithms-and-data-structures/javascript-algorithms-and-data-structures-projects.json#L370

**Comment by gforce2k5** [comment]
I'll fix it
