### ISSUE TITLE
Update the Contributing documentation

### ISSUE THREAD

**Issue by mattlub** [freeCodeCamp/curriculum#61]
Some potential contributors are having a problem with the Travis CI test which is checking for commit formats, but this is undocumented.

This repo should have a CONTRIBUTING.md file I guess containing this sort of information?

I am not really aware of the circumstances of moving from the old repo to this new repo- maybe it is appropriate to simply link to the CONTRIBUTING.md file from the old repo.

**Comment by raisedadead** [comment]
@scissorsneedfoodtoo 

When you have a minute can you please help us with moving over the documentation over to this repo?

I am thinking if you could create the points that need to be brought in from the main repo, someone can update the guide.

We would also need to create the same set of issue labels (with description), a triaging guide and the challenge style guides with the new schema.

And the issue templates from the main repo.

**Comment by scissorsneedfoodtoo** [comment]
@raisedadead, sure, I was thinking the same thing. I'll get to work moving over and editing the Contributing Guide from the main repo. I'll also start working on the issue labels, templates, and other guides soon, too.

**Comment by mattlub** [comment]
@scissorsneedfoodtoo re the issues, I've used this before: https://github.com/dwyl/labels

**Comment by scissorsneedfoodtoo** [comment]
@mattlub, thank you! That will be really helpful later.

**Comment by scissorsneedfoodtoo** [comment]
@raisedadead, I copied over all the labels from the main repo: https://github.com/freeCodeCamp/curriculum/labels

The only difference now is the first one, duplicate. However, I think people are good about self regulating and tend to close issues / pull requests themselves, so it's probably not necessary. Also, a number of the labels won't be necessary here, like some of the scope, other, and support ones. Just thought I'd leave them for completeness, and we can go back to delete the ones we definitely won't need later.

**Comment by raisedadead** [comment]
> we can go back to delete the ones we definitely won't need later.

Agreed. 

Thanks a lot for taking the time to make this changes.
