### ISSUE TITLE
Regex to test for Template Literals is incorrect 

### ISSUE THREAD

**Issue by RobAnthony01** [freeCodeCamp/curriculum#65]
**Describe the bug**
The regex string to test is the user has correctly used template literals is incorrect and the test fails when it should not.
Some of the escape characters in the string are not correctly entered, causing the error.

**To Reproduce**
1. Go to ES6: Create Strings using Template Literals
2. Complete the task
3. Click on Run the Tests
4. The test for "Template strings were used" will fail.

**Expected behavior**
The test should pass when template literals are correctly used.

**Screenshots**
![image](https://user-images.githubusercontent.com/29752205/41979784-c9dba7b4-7a1c-11e8-9d3a-ff35817a4efa.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser : Chrome
 - Version:  67.0.3396.99 (Official Build) (64-bit)

I'm happy to correct this issue.

**Comment by gforce2k5** [comment]
on it
